// "use client"
// These styles apply to every route in the application
// import './globals.css'
import '../../public/assets/css/style.css'
import '../../public/assets/css/tailwind.css'
import Head from 'next/head'
import Script from 'next/script'

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}) {

    return (
        <div lang="en">
            <Head>
                <title>Factory Universe</title>
                <link rel="manifest" href="../manifest.json" />
            </Head>

            <div id='root' className="bg-white dark:bg-slate-900">{children}</div>
            <Script src='../assets/js/uikit.min.js' />
            <Script src='../assets/js/script.js' />
            <Script src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js' />
            <Script src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js' />
        </div>
    )
}